// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqewdwwvnxdljlbtaxnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxZXdkd3d2bnhkbGpsYnRheG56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNjY4NTYsImV4cCI6MjA3MTc0Mjg1Nn0.dutC486MnRPiG9aw-HAX8WDzpldspQEw3fnFX4bJeq8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});